#!/usr/bin/env bash
set -euo pipefail

source_root="${POSE_SOURCE_ROOT:-$(cd "$(dirname "$0")/../../.." && pwd)}"
work_root="$(mktemp -d)"
project_root="$work_root/project"
cleanup() { rm -rf "$work_root"; }
trap cleanup EXIT

pose_bin="${POSE_BIN:-}"
if [[ -z "$pose_bin" ]]; then
  pose_bin="$work_root/pose"
  GOCACHE="${GOCACHE:-$work_root/gocache}" go -C "$source_root/pose-mcp" build -trimpath -o "$pose_bin" ./cmd/pose
fi

mkdir -p "$project_root"
cd "$project_root"
git init -q
git config user.name "POSE Review Bundle E2E"
git config user.email "pose-review-bundle@example.invalid"
"$pose_bin" install "$project_root" >/dev/null
git add .
git commit -qm "test: initialize POSE fixture"

mkdir -p app .pose/specs/review-bundle-e2e
cat > app/go.mod <<'EOF'
module example.invalid/review-bundle-e2e

go 1.24
EOF
cat > app/main.go <<'EOF'
package app

func Ready() bool { return true }
EOF
cat > app/main_test.go <<'EOF'
package app

import "testing"

func TestReady(t *testing.T) {
	if !Ready() { t.Fatal("not ready") }
}
EOF
cat > .pose/specs/review-bundle-e2e/spec.md <<'EOF'
---
slug: review-bundle-e2e
status: in-progress
created_at: 2026-08-13
components: app
delivers: contract:review-bundle-e2e
---

# Spec: Review Bundle E2E

## 1. Intent

### Goal
Prove that one review cycle converges.

## 2. Requirements

- R1: The bundle shall remain current after derived closeout updates.

## 3. Technical Plan

### Artifacts
- created: app/go.mod
- created: app/main.go
- created: app/main_test.go
- created: .pose/specs/review-bundle-e2e/spec.md

### Delivery targets
- contract:review-bundle-e2e module:app profile:api-contract entrypoint:app/main.go

### Risks
The fixture is isolated and offline.

## 4. Tasks
- [x] Implement the fixture.

## 5. Decisions
Use the local portable bundle contract.

## 6. Validation

### Requirement trace
- R1 [satisfied] test:review-bundle-e2e

### Execution log
Validation is generated by the e2e flow.

## 7. Final Report
Pending closeout.
EOF

base_commit="$(git rev-parse HEAD)"
git add app .pose/specs/review-bundle-e2e/spec.md
git commit -qm $'test: add review bundle fixture\n\nPOSE-Spec: review-bundle-e2e'
head_commit="$(git rev-parse HEAD)"
"$pose_bin" report \
  --task review-bundle-e2e \
  --spec review-bundle-e2e \
  --outcome pass \
  --change-from "$base_commit" \
  --change-to "$head_commit" >/dev/null
"$pose_bin" index >/dev/null
"$pose_bin" validate --strict --module app --json .pose/results/delivery-validation.json >/dev/null
"$pose_bin" index >/dev/null

policy_tmp="$work_root/review-policy.json"
jq '.review_bundles = true | .review_bundles_adopted_at = "2026-08-13"' .pose/policy/review.json >"$policy_tmp"
mv "$policy_tmp" .pose/policy/review.json

bundle_json="$work_root/bundle.json"
"$pose_bin" review bundle spec:review-bundle-e2e --seal --json >"$bundle_json"
bundle_id="$(jq -r .bundle_id "$bundle_json")"
plan_digest="$(jq -r .payload.plan.plan_digest "$bundle_json")"
bundle_digest="$(jq -r .bundle_digest "$bundle_json")"

"$pose_bin" review attest "$bundle_id" \
  --reviewer agent:independent-e2e \
  --decision approved \
  --plan-digest "$plan_digest" \
  --evidence requirement-trace:review-bundle-e2e \
  --evidence test:review-bundle-e2e \
  --evidence validation:review-bundle-e2e \
  --tool 'artifact-check|-|passed|requirement-trace:review-bundle-e2e|e2e' \
  --tool 'validate|app|passed|validation:review-bundle-e2e|e2e' \
  --tool 'validate|-|passed|validation:review-bundle-e2e|e2e' \
  --apply >/dev/null
"$pose_bin" review verify spec:review-bundle-e2e --json >"$work_root/verified.json"
jq -e '.state == "ready-to-close" and .approved == true' "$work_root/verified.json" >/dev/null

sed -i '0,/status: in-progress/s//status: done\ncompleted_at: 2026-08-13/' .pose/specs/review-bundle-e2e/spec.md
sed -i '0,/Pending closeout\./s//Delivered and verified./' .pose/specs/review-bundle-e2e/spec.md

"$pose_bin" review verify spec:review-bundle-e2e --json >"$work_root/closed.json"
jq -e --arg digest "$bundle_digest" '.state == "closed" and .approved == true and .bundle.bundle_digest == $digest' "$work_root/closed.json" >/dev/null
printf 'review-bundle-e2e=pass\nbundle_id=%s\nbundle_digest=%s\n' "$bundle_id" "$bundle_digest"
