package pose

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// repoRootForClaims locates this repository from the test's working directory,
// so the baseline runs against the real spec corpus and skips elsewhere.
func repoRootForClaims(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("../../..")
	if err != nil {
		t.Skipf("repository root unavailable: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, ".pose", "specs")); err != nil {
		t.Skipf("spec registry unavailable at %s: %v", root, err)
	}
	return root
}

// artifactClaimsUntilNextSubheading is the boundary rule as it was: the section
// ended only at another `### `. It is kept here, in the test, so the fix can be
// measured against it instead of against a golden file that would have to be
// regenerated by the thing it is supposed to check.
func artifactClaimsUntilNextSubheading(body string) (lines []string, found bool) {
	inSection := false
	for _, raw := range strings.Split(strings.ReplaceAll(body, "\r\n", "\n"), "\n") {
		line := strings.TrimSpace(raw)
		if line == "### Artifacts" {
			inSection, found = true, true
			continue
		}
		if inSection && strings.HasPrefix(line, "### ") {
			break
		}
		if inSection && strings.HasPrefix(line, "- ") {
			lines = append(lines, line)
		}
	}
	return lines, found
}

func claimPaths(claims []ArtifactClaim) []string {
	paths := []string{}
	for _, claim := range claims {
		paths = append(paths, claim.Action+":"+claim.Path+claim.OldPath+claim.NewPath)
	}
	return paths
}

// R3: the scaffold's own layout. `pose new-spec` writes `## 4. Tasks` right after
// the Technical Plan, so a spec that declares artifacts and adds no further `###`
// subsection had every task line read as a claim.
func TestArtifactClaimsSectionEnd(t *testing.T) {
	scaffoldShaped := Spec{Slug: "scaffold-shaped", Body: `## 3. Technical Plan

### Artifacts

- created: internal/thing.go
- modified: README.md

## 4. Tasks

- [ ] Reproduce the defect before changing the message.
- [x] Ship the fix.

## 5. Decisions

- Something that is not a claim either.
`}
	claims, found, err := ParseArtifactClaims(scaffoldShaped, ArtifactPolicy{})
	if err != nil {
		t.Fatalf("the scaffold layout still fails to parse: %v", err)
	}
	if !found {
		t.Fatal("the Artifacts section was not found")
	}
	if want := []string{"created:internal/thing.go", "modified:README.md"}; !reflect.DeepEqual(claimPaths(claims), want) {
		t.Fatalf("claims = %v, want %v — a task line or a decision bullet leaked in", claimPaths(claims), want)
	}
	// The old rule is what produced the malformed claim, and saying so here keeps
	// the test honest about what changed rather than only about what now passes.
	if lines, _ := artifactClaimsUntilNextSubheading(scaffoldShaped.Body); len(lines) != 5 {
		t.Fatalf("the previous rule no longer reproduces the defect it is here to represent: %v", lines)
	}

	// A heading of any level ends it, including a deeper one and a bare `##`.
	for name, body := range map[string]string{
		"deeper-heading": "### Artifacts\n\n- created: a.go\n\n#### Notes\n\n- [ ] not a claim\n",
		"top-heading":    "### Artifacts\n\n- created: a.go\n\n# Appendix\n\n- [ ] not a claim\n",
		"same-level":     "### Artifacts\n\n- created: a.go\n\n### Delivery targets\n\n- surface:x module:m profile:p entrypoint:e\n",
	} {
		t.Run(name, func(t *testing.T) {
			got, _, err := ParseArtifactClaims(Spec{Slug: name, Body: body}, ArtifactPolicy{})
			if err != nil {
				t.Fatalf("%s: %v", name, err)
			}
			if want := []string{"created:a.go"}; !reflect.DeepEqual(claimPaths(got), want) {
				t.Fatalf("%s: claims = %v, want %v", name, claimPaths(got), want)
			}
		})
	}
}

// R2: no existing spec loses a claim. Measured against the previous rule over
// every spec in this repository, not against a recorded count: where the two
// agree the fix changed nothing, and where they differ the previous rule must be
// the one that was reading past the end of its section.
func TestArtifactClaimsRepositoryBaseline(t *testing.T) {
	store := Store{Root: repoRootForClaims(t)}
	specs, err := store.ListSpecs("", "")
	if err != nil {
		t.Skipf("spec registry unavailable: %v", err)
	}
	if len(specs) < 50 {
		t.Skipf("baseline needs this repository's spec corpus, found %d", len(specs))
	}
	compared := 0
	for i := range specs {
		// ListSpecs returns frontmatter without bodies, so the body has to be
		// fetched. Measuring the listing's empty Body would have reported a clean
		// baseline over nothing, which is what the final assertion here guards.
		spec, err := store.GetSpec(specs[i].Slug)
		if err != nil || spec == nil {
			continue
		}
		oldLines, oldFound := artifactClaimsUntilNextSubheading(spec.Body)
		claims, found, parseErr := ParseArtifactClaims(*spec, ArtifactPolicy{})
		if found != oldFound {
			t.Errorf("%s: section detection changed (was %v, now %v)", spec.Slug, oldFound, found)
			continue
		}
		if !found {
			continue
		}
		if parseErr != nil {
			t.Errorf("%s: claims no longer parse: %v", spec.Slug, parseErr)
			continue
		}
		compared++
		if len(claims) > len(oldLines) {
			t.Errorf("%s: the new rule invented claims (%d vs %d bullets)", spec.Slug, len(claims), len(oldLines))
		}
		// Every bullet the previous rule read that is a real claim action must
		// still be a claim. A bullet it read that is not — a task checkbox, a
		// prose bullet from the next section — is the defect, and losing it is
		// the fix rather than a regression.
		for _, line := range oldLines {
			value := strings.TrimPrefix(line, "- ")
			action, _, ok := strings.Cut(value, ":")
			if !ok {
				continue
			}
			switch strings.TrimSpace(action) {
			case "created", "modified", "removed", "renamed", "none":
			default:
				continue
			}
			kept := false
			for _, claim := range claims {
				if strings.Contains(line, claim.Path) || strings.Contains(line, claim.NewPath) || claim.Action == "none" {
					kept = true
					break
				}
			}
			if !kept {
				t.Errorf("%s: lost a valid claim the previous rule read: %q", spec.Slug, line)
			}
		}
	}
	if compared == 0 {
		t.Fatal("no spec in this repository declares artifacts; the baseline measured nothing")
	}
	t.Logf("compared claim sets for %d specs declaring artifacts", compared)
}
