#!/usr/bin/env bash
# Benchmark governance operations on this repository (spec
# pose-governance-wait-rework-observability). Time and bytes are reported
# separately, with the corpus (revision) and the engine version, so two runs
# are comparable only when both match. Nothing here is a score.
#
# Usage: scripts/bench-governance.sh [runs] [pose-binary]
set -euo pipefail

runs="${1:-3}"
pose_bin="${2:-pose}"
root="$(git rev-parse --show-toplevel)"
cd "$root"

revision="$(git rev-parse HEAD)"
engine="$("$pose_bin" version 2>/dev/null | sed -n '1p')"
index_file=".pose/indexes/delivery-integrity.json"

median() {
  sort -n | awk '{ values[NR] = $1 } END { if (NR == 0) { print 0; exit } if (NR % 2) { print values[(NR + 1) / 2] } else { print (values[NR / 2] + values[NR / 2 + 1]) / 2 } }'
}

measure() {
  local name="$1"
  shift
  local samples=()
  local i start end
  for ((i = 1; i <= runs; i++)); do
    start="$(date +%s%N)"
    env -u POSE_PROJECT_ROOT -u POSE_PROJECT_ROOTS -u POSE_DEFAULT_PROJECT_ID "$pose_bin" "$@" >/dev/null 2>&1 || true
    end="$(date +%s%N)"
    samples+=("$(((end - start) / 1000000))")
  done
  local med
  med="$(printf '%s\n' "${samples[@]}" | median)"
  printf '{"operation":"%s","runs":%d,"median_ms":%s,"samples_ms":[%s]}\n' "$name" "$runs" "$med" "$(IFS=,; echo "${samples[*]}")"
}

printf '{"corpus_revision":"%s","engine":"%s","runs":%d}\n' "$revision" "$engine" "$runs"
measure "state-attention" state --attention
measure "check-strict" check --strict
measure "index" index
if [ -f "$index_file" ]; then
  printf '{"artifact":"%s","bytes":%d}\n' "$index_file" "$(wc -c <"$index_file")"
fi
# Generated by the run itself; leave the tree as it was.
git checkout -- .pose/indexes .pose/state 2>/dev/null || true
